### ISSUE TITLE
Improve the readme file

### ISSUE THREAD

**Issue by annu12340** [annu12340/SumIt#1]
Update the readme file with:-

Better description in the readme
Installation steps

Take these repos as example
https://github.com/annu12340/virtual-white-board
https://github.com/annu12340/Choose-Smart

**Comment by Shivamishra21** [comment]
I would like to work on this project.

**Comment by annu12340** [comment]
Go ahead @Shivamishra21

**Comment by Shivamishra21** [comment]
@annu12340 Sorry bt i want to ask which readme file i need to update??

**Comment by Shivamishra21** [comment]
I have to make a fresh new readme??

**Comment by annu12340** [comment]
> @annu12340 Sorry bt i want to ask which readme file i need to update??

This is the readme that you need to update
https://github.com/annu12340/SumIt/blob/master/README.md

**Comment by annu12340** [comment]
Solved
